# Generated by Django 2.2 on 2023-02-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230216_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
